// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}

// A temporary and interactive information between the server and the user.
type Session struct {
	// A unique string for identifying the user.
	Jwt string `json:"jwt"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
